services:
  mysql:
    image: mysql:8.0.37
    environment:
      - MYSQL_DATABASE=rebus2_test
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
